signup/urls.py
from django.conf.urls.defaults import *
import views, views.user, views.statistics
from django.views.generic.simple import direct_to_template
from tasks.views import home

################################################################################
urlpatterns = patterns('casestudies',
    url(r'^$', views.home, name="home"),
    url(r'^home2$', views.home2, name="home2"),
    url(r'^welcome$', home, name="welcome"),
    
    url(r'^users/(?P<id>[\w-]+)/$',
        views.user.user,
        name="user"),
    url(r'^users/(?P<id>[\w-]+)/edit$',
        views.user.edit_user,
        name="edit_user"),
    url(r'^constituencies/(?P<slug>[\w-]+)/users/$',
        views.user.all_users,
        name="all_users"),
    url(r'^login/(?P<key>\w+)/$',
        views.user.do_login,
        name="login"),
    url(r'^logout/$',
        views.user.do_logout,
        name="logout"),
    url(r'^reminder$',
        views.user.email_reminder,
        name="email_reminder"),
    url(r'^unsubscribe/(?P<key>\w+)/$',
        views.user.unsubscribe,
        name="unsubscribe"),
    
    url(r'^constituencies/$',
        views.constituencies,
        name="constituencies"),
    url(r'^constituencies/(?P<slug>[\w-]+)/$',
        views.constituency,
        name="constituency"),
    url(r'^constituencies/(?P<slug>[\w-]+)/(?P<login_key>[\w-]+)$',
        views.constituency,
        name="constituency"),
    url(r'^constituencies/(?P<slug>[\w-]+)/(?P<year>\d+)/$',
        views.constituency,
        name="constituency-by-year"),
    url(r'^add_constituency/$',
        views.add_constituency,
        name="add_constituency"),
    url(r'^delete_constituency/(?P<slug>[\w-]+)/$',
        views.delete_constituency,
        name="delete_constituency"),

    url(r'^statistics/fewerthan/(?P<volunteers>\d+)/geo.rss$',
        views.statistics.constituencies_with_fewer_than_rss,
        name="constituencies_with_fewer_than_rss"),
    url(r'^statistics/morethan/(?P<volunteers>\d+)/geo.rss$',
        views.statistics.constituencies_with_more_than_rss,
        name="constituencies_with_more_than_rss"),
    url(r'^statistics/$',
        views.statistics.statistics,
        name="statistics"),
    url(r'^statistics/heatmap.svg$',
        views.statistics.generate_map_2010,
        name="map"),
    url(r'^statistics/(?P<date>[\w-]+)/heatmap.svg$',
        views.statistics.generate_map_2010,
        name="map_on_date"),
    url(r'^manage$',
        direct_to_template,
        {'template':'manage.html'},
        name="manage"),
                      
)

urls.py
from django.conf.urls.defaults import *
from settings import MEDIA_ROOT
from django.views.static import serve
from issue.feeds import AllIssues

import signup

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

feeds = {
    'allissues': AllIssues,
    }

urlpatterns = patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enablese admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^media/(?P<path>.*)$', serve,
     {'document_root': MEDIA_ROOT,
      'show_indexes': True}),
    ('^invite/', include('invite.urls')), 
    ('^tsc/', include('tsc.urls')),
    ('^tasks/', include('tasks.urls')),
    ('^issues/', include('issue.urls')),
    ('^s/', include('shorten.urls')),
    ('^meetings/', include('meetings.urls')),
    (r'^comments/core/', include('django.contrib.comments.urls')),
    (r'^comments/', include('comments_custom.urls')),
    (r'^ynmp/', include('ynmp.urls')),
    (r'^twfy/', include('twfy.urls')),
    ('^', include('signup.urls')),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
     {'feed_dict': feeds}),       
)

twfy/models.py
from django.db import models

from signup.models import Model
from issue.models import RefinedIssue

from ynmp.models import Candidacy

class Statement(Model):
    twfy_key = models.CharField(max_length=20)
    refined_issue = models.ForeignKey(RefinedIssue,
                                      blank=True,
                                      null=True)
    question = models.CharField(max_length=350,
                                blank=True,
                                null=True)
    national = models.BooleanField(default=False)

class SurveyResponse(Model):
    candidacy = models.ForeignKey(Candidacy)
    statement = models.ForeignKey(Statement)
    national = models.BooleanField(default=False)
    # 100 = strongly agree, 0 = strongly disagree
    agreement = models.IntegerField()
    more_explanation = models.TextField()
                                        
class SurveyInvite(Model):
    ynmp_id = models.CharField(max_length=9)
    candidacy = models.ForeignKey(Candidacy,
                                  blank=True,
                                  null=True)
    emailed = models.BooleanField(default=False)
    filled_in = models.BooleanField(default=False)
    survey_token = models.CharField(max_length=30,
                                    blank=True,
                                    null=True)
    pester_emails_sent = models.IntegerField(default=0)

    def __unicode__(self):
        number_emails = self.pester_emails_sent
        if self.emailed:
            number_emails += 1
        return "%s\t%s\t%s\t%d\t%s" % \
               (self.candidacy.candidate.name,
                self.candidacy.candidate.email,
                unicode(self.candidacy.candidate.party.name),
                number_emails,
                self.filled_in)

signup/views.py
import types
from itertools import takewhile
import re

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.html import escape
from django.utils.safestring import SafeUnicode
from django.contrib.sites.models import Site
from django.template.loader import render_to_string
from django.core.mail import send_mail

import models
from models import CustomUser, Constituency, RegistrationProfile
from forms import UserForm
import signals
import utils

from utils import addToQueryString
import settings
import geo


def render_with_context(request,
                        template,
                        context,
                        **kw):
    kw['context_instance'] = RequestContext(request)
    return render_to_response(template,
                              context,
                              **kw)


def _get_statistics_context():
    context = {}
    year = settings.CONSTITUENCY_YEAR
    constituencies = Constituency.objects.filter(year=year)
    volunteers = CustomUser.objects.filter(is_active=True)
    count = constituencies.filter(customuser__in=volunteers)\
            .distinct()\
            .count()
    total = constituencies.count()
    
    context['volunteers'] = volunteers.count()
    context['total'] = total
    context['count'] = count
    if total:
        percent = int(float(count)/total*100)
        context['percent_complete'] = percent
    else:
        context['percent_complete'] = 0
    context['new_signups'] = CustomUser.objects.order_by('-date_joined')\
                                               .filter(can_cc=True)[:5]
    return context

def home(request):
    context = _get_statistics_context()
    if request.user.is_anonymous():
        if request.method == "POST":
            form = UserForm(request.POST, request.FILES)
            if form.is_valid():
                profile = form.save()
                user = authenticate(username=profile.user.email)
                login(request, user)
                return HttpResponseRedirect(reverse('welcome'))
            else:
                context['form'] = form
        else:
            context['form'] = UserForm()
        return render_with_context(request,
                               'home.html',
                               context)
    else:
        return HttpResponseRedirect(reverse('welcome'))

def home2(request):
    context = _get_statistics_context()
    if request.user.is_anonymous():
        if request.method == "POST":
            form = UserForm(request.POST, request.FILES)
            if form.is_valid():
                profile = form.save()
                user = authenticate(username=profile.user.email)
                login(request, user)
                return HttpResponseRedirect(reverse('welcome'))
            else:
                context['form'] = form
        else:
            context['form'] = UserForm()
        return render_with_context(request,
                               'home_2.html',
                               context)
    else:
        return HttpResponseRedirect(reverse('welcome'))

@login_required
def delete_constituency(request, slug):
    c = Constituency.objects.get(slug=slug)
    request.user.constituencies.remove(c)
    request.user.save()
    return HttpResponseRedirect(reverse('add_constituency'))


def search_place(place):
    "Search for place, return constituencies with that name"
    foundplace = geo.constituency(place)
    if foundplace:
        return Constituency.objects.filter(name__in=foundplace)
    else:
        return []

def search_name(place):
    "constituencies that have place in their name"
    return Constituency.objects\
        .filter(name__icontains=place)\
        .order_by('name')

def feedback(msg, place):
    "search feedback"
    return SafeUnicode(escape(msg) + (u"&nbsp;<b>%s</b>:" % escape(place)))

def place_search(place):
    """
    Attempt to find the constituency for a place.

    Place can be a postcode, the name of a town, or the name of a constituency
    Returns a mapping that can be included in a context
    """
    results = []
    foundplace = search_place(place)
    if len(foundplace) > 0:
        if len(foundplace) == 1:
            fb = feedback("We found one constituency matching", place)
        else: 
            fb = feedback("We found these constituencies near", place)
        results.append((fb, foundplace))

    foundname = search_name(place)
    # some constituencies have exactly the same name as a town (eg
    # Nuneaton), they should not appear twice
    foundname = foundname.exclude(pk__in=foundplace)

    if len(foundname) > 0:
        fb = feedback("We found these constituencies containing", place)
        results.append((fb, foundname))
        
    if len(foundname) == 0 and len(foundplace) == 0:
        fb = feedback("Alas, we can't find", place)
        results.append((fb, []))

    return results


@login_required
def add_constituency(request):
    my_constituencies = []
    if request.user.ordered_constituencies:
        my_constituencies = request.user.ordered_constituencies.all()
    context = {'my_constituencies': my_constituencies}
    context['constituencies'] = []
    tick_instructions = "Tick a box and scroll"
    if len(my_constituencies) > 0:
        try:
            const = my_constituencies[0]
            all_const = Constituency.objects.exclude(
                pk__in=my_constituencies)
            neighbours = const.neighbors(limit=5,
                                         constituency_set=all_const)
            missing = models.filter_where_customuser_fewer_than(1)
            missing_neighbours = const.neighbors(
                limit=5,
                constituency_set=missing)

            context["search_results"] = [
                (feedback("We found these constituencies near", const.name),
                 neighbours)]
            context["missing_search_results"] = [
                (feedback(("These are the nearest places where there "
                           "aren't any volunteers yet"), ""),
                 missing_neighbours)]
        except KeyError:
            # Any problems looking up neighbours means we pretend to
            # have none
            pass

    # searching for a constituency by postcode or placename
    if request.method == "GET":
        if request.GET.has_key("q"):
            place = request.GET["q"]
            if not place.strip():
                context['search_results'] = (
                    "Please enter a postcode or place name", [])
            else:
                context["search_results"] = place_search(place)

    # adding another constituency
    if request.method == "POST":
        if request.POST.has_key('add') and request.POST.has_key('add_c'):
            add_c = request.POST.getlist('add_c')
            if type(add_c) != types.ListType:
                add_c = [add_c]
            constituencies = Constituency.objects.all().filter(slug__in=add_c)
            constituencies = constituencies.exclude(pk__in=my_constituencies)
            request.user.constituencies.add(*constituencies.all())
            request.user.save()
            signals.user_join_constituency.send(None,
                                                user=request.user,
                                                constituencies=constituencies.all())

            return HttpResponseRedirect("/add_constituency/")

    return render_with_context(request,
                               'add_constituency.html',
                               context)

def do_login(request, key):
    profile = RegistrationProfile.objects.get_user(key)
    if profile:
        user = authenticate(username=profile.user.email)
        login(request, user)
        signals.user_login.send(None, user=user)
    return HttpResponseRedirect("/")
    
def activate_user(request, key):
    profile = RegistrationProfile.objects.activate_user(key)
    error = notice = ""
    if not profile:
        error = "Sorry, that key was invalid"
    else:
        notice = "Thanks, you've successfully confirmed your email"
        user = authenticate(username=profile.user.email)
        login(request, user)
    context = {'error': error,
               'notice': notice}
    return HttpResponseRedirect(addToQueryString("/", context))

def user(request, id):
    from tasks.models import TaskUser
    context = {}
    user = get_object_or_404(CustomUser, pk=id)
    context['profile_user'] = user
    context['activity'] = TaskUser.objects.\
        filter(user=user).\
        filter(user__can_cc=True).\
        filter(state__in=[TaskUser.States.started,TaskUser.States.completed]).\
        order_by('-date_modified').distinct()
    context['badges'] = user.badge_set.order_by('-date_awarded')
    return render_with_context(request,
                               'user.html',
                               context)

def constituency(request, slug, year=None):
    from tasks.models import TaskUser

    if year:
        year = "%s-01-01" % year
    else:
        year = settings.CONSTITUENCY_YEAR

    try:
        constituency = Constituency.objects.all()\
                       .filter(slug=slug, year=year).get()
    except Constituency.DoesNotExist:
        raise Http404

    if request.method == "POST":
        context = {'constituency': constituency}
        within_km = int(request.POST['within_km'])
        nearest = constituency.neighbors(limit=100,
                                         within_km=within_km)
        context['nearest'] = nearest
        context['subject'] = request.POST['subject']
        context['message'] = request.POST['message']
        context['within_km'] = within_km

signup/templates/activate.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock %}

{% block content %}

{% if error %}

Oh noes!

{% else %}

Hello you are activated

{% endif %}


{% endblock %}

signup/templates/add_constituency.html
{% extends 'base.html' %}
{% block title %}Join more constituencies{% endblock %}

{% block content %}

<div class="span-3 box">
<h2>Your constituencies</h2>
{% if my_constituencies %}
 <p>You are currently signed up as a volunteer in:</p>

  <ul id="my-constituency-list">
   {% for c in my_constituencies %}
   <li>
    <a href="{% url constituency slug=c.slug %}">{{ c.name }}</a>
    <a href="{% url delete_constituency slug=c.slug %}"
       onclick="if(!window.confirm('Are you sure you want to leave {{ c.name }}?')) return false">(leave)</a>
   </li>
   {% endfor %}
  </ul>
{% else %}
 <p>You're not signed up for any constituencies.  Try typing your postcode or home town into the search box.</p>
{% endif %}
</div>
<div class="span-4 last">

{% include "more_constituencies_form.html" %}

</div>

{% endblock %}

signup/templates/all_users.html
{% extends 'base.html' %}
{% load comments %}
{% load signup_extras %}

{% block title %}{{constituency.name}}{% endblock %}
{% block section %}allusers{% endblock %}

{% block extra-head %}
<link rel="stylesheet" type="text/css"  media="screen" href="{{ MEDIA_URL }}constituency/constituency.css" />
{% endblock %}

{% block content %}
<h1>All users in {{ constituency.name }}</h1>

<p><a href="{{ constituency.get_absolute_url }}">back to constituency page</a></p>

<ul class="users">
{% for user in users %}
    <li>{{ user.display_name }}{% if show_email %}{% if user.can_cc %} (<a href='mailto:{{ user.email }}'>{{ user.email }}</a>){% endif %}{% endif %}</li>
{% endfor %}
</ul>

{% endblock %}

signup/templates/candidacy_listitem.html
	{% if not candidacy.surveyinvite_set.get.filled_in %}
	 <input type="hidden" name="candidacy_{{candidacy.pk}}" checked="checked" value="1" />
	{% endif %}
        {% if candidacy.candidate.party.image_url %} 
          <img src="{{ candidacy.candidate.party.image_url}}" alt="{{ candidacy.candidate.party.name }}" title="{{ candidacy.candidate.party.name }}">
        {% endif %}
        {{ candidacy.candidate.name }} 
        {% if not candidacy.candidate.party.image_url %} 
	  ({{ candidacy.candidate.party.name }})
	{% endif %}

signup/templates/constituency_comment.html
{% load comments %}
{% load signup_extras %}

<a id="comments"></a><h3>{{ constituency.name }} discussion</h3>
{% if can_post %}
{% if not user.is_anonymous %}{% if user.is_active %}
<p class="quiet">Discuss with other people what you're doing in this constituency.</p>

<script>
function update_notify()
{
    /*state = $('input#notify').value;
    alert(state);*/
    $('#notifyform').submit();
}
</script>

{% with notify_object as notify %}
  <form method="post" id="notifyform">
    <input type="hidden" name="notifypost" value="1"/>
    <label for="notify">Email me when someone posts here</label>
    {% if notify %}
         <input name="notify" type="checkbox" value="yes" {% ifnotequal notify.notify_type 0 %}checked{% endifnotequal %} onchange="update_notify()"/>
    {% else %}
         <input name="notify" type="checkbox" value="yes" onchange="update_notify()"/>
    {% endif %}
    <input type="submit" value="save"/>
  </form>
{% endwith %}

{% get_comment_form for constituency as form %}
<form action="{% comment_form_target %}" method="post" id="post-comment">
  {{ form.content_type }}
  {{ form.object_pk }}
  {{ form.timestamp }}
  {{ form.security_hash }}
  <input type="hidden" name="next" value="{{ request.path }}#comments" />
  <input id="id_comment" name="comment" value="write here" onfocus="if(this.value=='write here') { this.value='' }" onblur="if(this.value==''){ this.value='write here'; }" maxlength="3000" type="text"> <input name="post" class="submit-post" value="post" type="submit">

  <p style="display: none; margin:0;">
    <label for="id_honeypot">If you enter anything in this field your comment will be treated as spam</label> {{ form.honeypot }}
  </p>
</form>
{% endif %}{% endif %}
{% endif %}

{% get_comment_list for constituency as comment_list %}
<div class="comments">
{% for comment in comment_list reversed %}
    <div class="comment">
        {#{% ifequal comment.user user %}<a href='#' style="float:right;">delete</a>{% endifequal %}#}
        {% if perms.delete_comment %}<a href='{% url custom_comment_delete comment.id,request.path %}' class="comment_action">delete</a>{% endif %}
        {% ifequal comment.removal_reason 'none' %}
            <span class="poster">{{ comment.user.display_name }}</span>
            <span class="text">{{ comment.comment }}</span>
        {% else %}
            <span class="text moderated">This comment was removed because: <a href='/moderation/#{{ comment.removal_reason }}'>{{ comment.long_removal_reason }}</a>.</span>
        {% endifequal %}
        <span class="time">{{ comment.submit_date|naturalTimeDifference }}</span>
    </div>
{% empty %}
    <div class="comment">There are no messages for {{ constituency.name }} yet{% if can_post %}, be the first!{% endif %}</div>
{% endfor %}
</div>

signup/templates/constituency_email.html
{% extends 'base.html' %}
{% block title %}{{constituency.name}}{% endblock %}

{% block content %}
{% if recipients %}
<p>Message sent to {{ recipients }} recipients</p>
{% if error_recipients %}
 <p>Error sending to:</p>
 <ul>
   {% for user in error_recipients %}
    <li>{{ user.email }}</li>
   {% endfor %}
 </ul>
{% endif %}
{% else %}
<p>I'll send your email to people in the constituencies listed below.</p>
<form method="post">
<ul>
 <li>Yes, please send it now <input type="submit" name="go" value="go" /></li>
 <li>Don't send it; show me constituencies within <input name="within_km" size="3" value="{{ within_km }}" />km instead <input type="submit" value="go" /></li>
</ul>

Subject: <input type="text" name="subject" value="{{ subject|safe }}" /><br />
<textarea name="message" cols="79" rows="12">{{ message|safe }}</textarea><br />
</form>
<hr />

{% for c in nearest %}
 {{ c }}<br />
{% endfor %}

{% endif %}

{% endblock %}

signup/templates/email_reminder.html
{% extends "base.html" %}

{% block title %}Resend login email{% endblock %}

{% block content %}
<h2>Send login email</h2>
{% for message in messages %}
<p class="notice">{{ message }}</p>
{% endfor %}
<p>On this site you don't log in with a username and password, but <strong>via a link in your email</strong>.  If you've lost your login link, enter your email here and we'll resend your welcome email.</p>

<form method="POST" action="{% url email_reminder %}">
<input type="text" name="email"/>
<input type="submit" value="send"/>
</form>
{% endblock %}

signup/templates/home.html
{% extends 'base.html' %}
{% load signup_extras %}
{% block extra-head %}
<link rel="stylesheet" type="text/css"  media="screen" href="{{ MEDIA_URL }}tasks/tasks.css" />
{% endblock %}

{% block title %}Transparency through volunteering{% endblock %}

{% block content %}
<div class="span-5">

<h2>Want to know what your parliamentary candidates think? Be part of the movement that's finding out.</h2>
<script type="text/javascript">
window.onload = function () { document.getElementById('id_first_name').focus(); }
</script>
<p><strong>Our volunteers have built <a href="http://election.theyworkforyou.com/quiz">the definitive guide to where all candidates stand on major issues, nationwide</a>.</strong></p>

<p>Join Democracy Club today to make sure your own candidates don't hide their views.</p>


{% if form %}
  <form action="" method="post" id="signup">
  <table>
  {{ form.as_table }}
  <tr>
   <td></td>
   <td><input type="submit" value="sign up" /></td>
  </tr>
  <tr>
   <td></td>
   <td class="small"><a href='{% url email_reminder %}'>Lost your login information?</a></td>
  </tr>
  </table>
  </form>
 {% endif %}
<p>
We are a <a href="/aboutus/">handful of volunteers</a> who care about democracy.  We occasionally suggest tasks by email that you might be interested in, <a href="/projects/">such as</a> gathering information on general election candidates. We'll also help you to collaborate with other volunteers in your area.
</p>
<!--<p>
We already know that mySociety wants to gather information on general election candidates, and TheStraightChoice wants you to help them find and share election leaflets. As the election approaches there'll be even more things to do, and you can be part of it.
</p>-->

<p class="small">We will occasionally suggest tasks on behalf of other transparency related groups, but we'll never share your private details with anyone, and we'll never send you more than two emails a week, no matter what.  Read our <a href="/aboutus/#privacy">terms and conditions</a> for more.</p>

</div>

<div class="span-3 last">

<h3>Questionnaire progress</h3>
<div id="visualization">
<img src="http://chart.apis.google.com/chart?chxt=x,y&cht=bvs&chd=s:cEj9U&chco=333399|cc0000|ff9900|73a532|ab1e94|999999&chls=2.0&chs=336x180&chxl=0:|Cons.|Lab.|Lib.Dem.|Green|UKIP|Ind.&chbh=a&chd=t:{% for party in parties %}{{party.replies_received|percentage:party.invites_sent}}{% if not forloop.last %},{% endif %}{% endfor %}&chds=0,{{ max_percentage }}&chxr=1,0,{{ max_percentage }},10" width="336" height="180" />
<!--<img src="http://chart.apis.google.com/chart?chxt=x,y&chxr=1,0,650,100&chds=0,650&cht=bvs&chco=333399|999999|cc0000|ff9900&chls=2.0&chs=336x180&chxl=0:|Con|Ind|Lab|Lib|&chbh=a&chd=t:{% for party in parties %}{{party.invites_sent}}{% if not forloop.last %},{% endif %}{% endfor %}" width="336" height="180" />-->
<p class="quiet" style="text-align:center">% survey response rate, by party</p>
</div>
<p>Surveys are now closed to candidates.  We sent questionnaires out to everyone we had contact details for. <a href="{% url chart %}">Some parties were better at replying than others</a>.  Thanks to our <strong>{{ volunteers }}</strong>-strong <a href="/statistics/">army of volunteers</a> for chasing them up!</p>
<p class="quiet"><a href='http://twitter.com/democlub' target="_blank">Follow us on Twitter</a> and <a href='http://www.facebook.com/pages/Democracy-Club/316731041785' target="_blank">become a fan on Facebook</a>!</p>
<p>
<h3>Recent signups</h3>
{% include "new_signup_list.html" %}
</p>


{% endblock %}

signup/templates/home_2.html
{% extends 'base.html' %}

{% block extra-head %}
<link rel="stylesheet" type="text/css"  media="screen" href="{{ MEDIA_URL }}tasks/tasks.css" />
{% endblock %}

{% block title %}Transparency through volunteering{% endblock %}

{% block content %}
<div class="span-5">

<h2>
Want to help fix democracy?
</h2>
<script type="text/javascript">
window.onload = function () { document.getElementById('id_first_name').focus(); }
</script>
<p>Join us in making this the most accountable election ever!</p>
<p><em><a href="/aboutus/">Democracy Club</a></em> is a non-partisan hub for for armchair activists. We suggest small ways in which volunteers can hold our representatives to account.</p>
<p>Interested? Read <a href='/faq/'>our FAQ</a> or jump right in below.</p>
</p>
{% if form %}
  <form action="" method="post" id="signup">
  <table>
  {{ form.as_table }}
  <tr>
   <td></td>
   <td><input type="submit" value="sign up" /></td>
  </tr>
  <tr>
   <td></td>
   <td class="small"><a href='{% url email_reminder %}'>Lost your login information?</a></td>
  </tr>
  </table>
  </form>
 {% endif %}
<p>
When you sign up, we will occasionally suggest tasks by email, <a href="/aboutus/#what">such as</a> gathering information on general election candidates for <a href='http://www.mysociety.org/'>mySociety</a> or finding and sharing election leaflets for <a href='http://www.thestraightchoice.org/'>The Straight Choice</a>, to help them build awesome sites that will make the next election the most transparent ever. We'll also help you to collaborate with other volunteers in your area.
</p>
<!--<p>
We already know that mySociety wants to gather information on general election candidates, and TheStraightChoice wants you to help them find and share election leaflets. As the election approaches there'll be even more things to do, and you can be part of it.
</p>-->

<p class="small">We will occasionally suggest tasks on behalf of other transparency related groups, but we'll never share your private details with anyone, and we'll never send you more than two emails a week, no matter what.  Read our <a href="/aboutus/#privacy">terms and conditions</a> for more.</p>

</div>

<div class="span-3 last">
<div id="visualization"></div>
<p>We're trying to get volunteers in every part of the UK.  So far, we've recruited {{ volunteers }} volunteers in {{ count }} constituencies (out of a total {{ total }}). <a href="/statistics/">Read more about how we're doing</a>. You can also <a href='http://twitter.com/democlub' target="_blank">follow us on Twitter</a> and <a href='http://www.facebook.com/pages/Democracy-Club/316731041785' target="_blank">become a fan on Facebook</a>.</p></p>
<p>
<h3>Recent signups</h3>
{% include "new_signup_list.html" %}
</p>

{% block js %}
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('visualization', '1', {packages: ['gauge']});
</script>
<script type="text/javascript">
function drawVisualization() {
  // Create and populate the data table.
  var data = new google.visualization.DataTable();
  data.addColumn('string', 'Label');
  data.addColumn('number', 'Value');
  data.addRows(1);
  data.setValue(0, 0, '% complete');
  data.setValue(0, 1, {{percent_complete}});

  // Create and draw the visualization.
  var chart = new google.visualization.Gauge(document.getElementById('visualization'));
  var opts = {redFrom: 90, 
              redTo: 100, 
              yellowFrom: 75,
              yellowTo: 90, 
              greenFrom: 35, 
              greenTo: 75};

   chart.draw(data, opts);
}
google.setOnLoadCallback(drawVisualization);
</script>
{% endblock %}


{% endblock %}

signup/templates/manage.html
{% extends 'base.html' %}
{% block title %}Management functions{% endblock %}

{% block content %}
<ul>
 <li>
  <a href="{% url moderate_issue %}">Moderate issues</a>
 </li>
 <li>
  <a href="{% url manage_tasks %}">Manage and track tasks</a>
 </li>
</ul>

{% endblock %}